# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Brandon's Blog
tagline:          'a daily blog'
description:      "One Java Student's Journey to Becoming a Junior Software Engineer"
url:              https://beefan.github.io/
baseurl:          https://beefan.github.io/

author:
  name:           'Brandon Fannin'
  url:            https://www.linkedin.com/in/brandon-fannin/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/beefan/beefan.github.io
