# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Brandon Fannin
tagline:          'a programmer'
description:      "Programmer. <a href="https://www.strava.com/athletes/brandonfannin">Distance runner</a>. Voracious learner."
url:              https://beefan.github.io/
baseurl:          https://www.brandonfannin.com/

author:
  name:           'Brandon Fannin'
  url:            https://brandonfannin.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/beefan/beefan.github.io
